# docker-compose.yml (PRODUCTION)
version: "3.8"

services:
    app:
        image: mrms_sp7:latest # <-- image akan di-load dari file .tar
        container_name: mrms_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - app_storage:/var/www/html/storage
            - ./.env:/var/www/html/.env:ro
        networks:
            - mrms_net
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    webserver:
        image: nginx:stable-alpine
        container_name: mrms_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - app_storage:/var/www/html/storage:ro
            - .:/var/www/html:ro
        networks:
            - mrms_net
        depends_on:
            - app

    db:
        image: postgres:17-alpine
        container_name: mrms_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - mrms_net

    queue:
        image: mrms_sp7:latest
        container_name: mrms_queue
        restart: unless-stopped
        command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
        volumes:
            - app_storage:/var/www/html/storage
            - ./.env:/var/www/html/.env:ro
        networks:
            - mrms_net
        depends_on:
            - app
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    scheduler:
        image: mrms_sp7:latest
        container_name: mrms_scheduler
        restart: unless-stopped
        command: /bin/sh -c "while true; do php artisan schedule:run --verbose --no-interaction & sleep 60; done"
        volumes:
            - app_storage:/var/www/html/storage
            - ./.env:/var/www/html/.env:ro
        networks:
            - mrms_net
        depends_on:
            - app
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

volumes:
    app_storage:
    db_data:

networks:
    mrms_net:
        driver: bridge
